-- 코드를 입력하세요
SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(s.SALES*b.PRICE) as "TOTAL_SALES"
FROM BOOK b
JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES s ON s.BOOK_ID = b.BOOK_ID AND  s.SALES_DATE >= "2022-01-01" AND s.SALES_DATE < "2022-02-01"
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY desc