-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (
    SELECT SHIPMENT_ID,FLAVOR,TOTAL_ORDER FROM JULY
    UNION ALL
    SELECT SHIPMENT_ID,FLAVOR,TOTAL_ORDER FROM FIRST_HALF
    
) A
GROUP BY A.FLAVOR
ORDER BY SUM(A.TOTAL_ORDER) DESC
LIMIT 3

