SELECT B.SCORE, B.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES A
JOIN HR_DEPARTMENT C
ON A.DEPT_ID = C.DEPT_ID
JOIN (
    SELECT SUM(SCORE) as SCORE, EMP_NO
    FROM HR_GRADE
    WHERE YEAR = "2022"
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
) as B 
ON A.EMP_NO = B.EMP_NO