SELECT A.DEPT_ID, A.DEPT_NAME_EN, B.AVG_SAL
FROM HR_DEPARTMENT A
JOIN (
    SELECT DEPT_ID, round(AVG(SAL)) as AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) B ON A.DEPT_ID = B.DEPT_ID
ORDER BY B.AVG_SAL DESC