-- 코드를 입력하세요
SELECT A.CATEGORY, B.MAX_PRICE ,A.PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN (
    SELECT CATEGORY, MAX(PRICE) as MAX_PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) B
ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.MAX_PRICE
WHERE A.CATEGORY in ("과자","국","김치","식용유")
ORDER BY B.MAX_PRICE desc